config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "companies#index"
  resources :companies do
    resources :products

  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :products, dependent: :destroy
  validates :name, uniqueness: :true, presence: :true
  belongs_to :user
end

app/models/product.rb
class Product <ActiveRecord::Base
  belongs_to :company
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :companies
end

app/controllers/CompaniesController.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.create!(company_params)
  end

  def show
    @company = Company.find(params[:id])
  end

  def edit
    @company = Company.find(params[:id])
  end
end

app/controllers/Companies_Controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.create!(company_params.merge(user: current_user))
    redirect_to (company_path(@company))

  end

  def show
    @company = Company.find(params[:id])
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)

    redirect_to @company
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path
  end


  private
  def company_params
    params.require(:company).permit(:name, :category, :location, :logo_url)
  end

end

app/controllers/ProductsController.rb
class ProductsController < ApplicationController

def index
  @products = Product.all
end

def show
  @product = Product.find(params[:id])
end

def new
  @company = Company.find(params[:company_id])
  @product = @company.products.create!(product_params)
end

def edit
  @product.find(params[:id])
end

def destroy
  @product = Product.find(params[:id])
  @product.destroy

end

end

app/controllers/Products_Controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

def index
  @company = Company.find(params[:company_id])
  @products = @company.products
end

def show
  @product = Product.find(params[:id])
end

def new
  @company = Company.find(params[:company_id])
  @product = Product.new
end

def create
  @company = Company.find(params[:company_id])
  @product = @company.products.create!(product_params)
  redirect_to company_products_path
end

def edit
  @product = Product.find(params[:id])
end

def destroy
  redirect_to root_path unless
  @product = Product.find(params[:id])
  @product.destroy
  redirect_to products_path
end

private
def product_params
  params.require(:product).permit(:name, :description, :price, :inventory, :vendor)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<div class="form">
  <%= form_for @company do |f| %>
  <div class="form_field">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <div class="form_field">
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div>
    <div class="form_field">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div class="form_field">
      <%= f.label :logo_url %>
      <%= f.text_field :logo_url %>
    </div>
    <div class="form_action">
      <%= f.submit %>
      <% end %>
    </div>
  </div>

  

app/views/companies/edit.html.erb
<h2>Edit Company</h2>

<div>
  <%= form_for @company do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :logo_url %>
  <%= f.text_field :logo_url %>

  <%= f.submit %>
  <% end %>

  <%= link_to "Delete", @company, method: :delete, class: "delete" %>

</div>

app/views/companies/index.html.erb
<% if !current_user %>
<div class "home">
<h1>Welcome !</h1>
</div>

<% elsif current_user %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        Companies
      </a>
    </div>
  </div>
</nav>
<div>
  <ul>
    <% @companies.each do |company| %>

    <div class "company_list">
      <li>
        <%= link_to company.name, company_path(company) %>
      </li>
      <% end %>
    </div>
  </ul>
  <%=link_to "add company", new_company_path %>
  <div>
    <% end %>

app/views/companies/new.html.erb
<h2>New Company</h2>

<div class="container">
  <%= form_for @company do |f| %>
  <div class="form_field">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <div class="form_field">
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div>
    <div class="form_field">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div class="form_field">
      <%= f.label :logo_url %>
      <%= f.text_field :logo_url %>
    </div>
    <div class="form_action">
      <%= f.submit %>
      <% end %>
    </div>
  </div>

app/views/companies/show.html.erb
<div class "">
  <h2><%= link_to @company.name, edit_company_path(@company)%></h2>
  <div class="logo" ><%= image_tag @company.logo_url, class:"company-logo"%>
  </div>
  <div class ="product_info">
    Products Inventory Summary
         <%= link_to "Products Details", company_products_path(@company) %>
  </div>
    <ul class="list-group">
  <% @company.products.each do |product| %>
    <li class="list-group-item">
      <%= link_to"#{product.name}", edit_company_product_path(@company, product)%> <div> </div>
      <%= link_to "#{product.inventory}", edit_company_product_path(@company, product)%>
    </li>
  <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventoryTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%=companies_path%>">
        Products Inventory Tracker
      </a>
      <button type="button" class="btn btn-default navbar-btn">
        <% if !current_user %>
  <%= link_to "Sign Up", new_user_registration_path %> |
  <%= link_to "Sign In", new_user_session_path%>
  <% else current_user %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
  <%end%>
        </button>
    </div>
    <p class="navbar-text navbar-right">
      <% if current_user %>
      Signed in as
      <a href="<%=@current_user_session_path%>" class="navbar-link">
    <%=current_user.email%>
      <%end%>
    </a></p>
  </div>
</nav>
<div class="container">
<%= yield %>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</body>
</html>

app/views/products/_form.html.erb
<div class "form">
<%= form_for @product do |f| %>
<div class="form_field">
<%= f.label :vendor_id %>
<%= f.text_field :vendor_id %>
</div>
<div class="form_field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="form_field">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>
<div class="form_field">
  <%= f.label :inventory %>
  <%= f.text_field :inventory %>
</div>
<div class="form_field">
  <%= f.label :price %>
  <%= f.text_field :price %>
</div>
<div class="form_action">
  <%= f.submit %>
<% end %>
</div>

app/views/products/edit.html.erb
<h2>Edit product</h2>

<div class "">
<%= form_for @product do |f| %>
<div class="form_field">
<%= f.label :vendor_id %>
<%= f.text_field :vendor_id %>
</div>
<div class="form_field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="form_field">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>
<div class="form_field">
  <%= f.label :inventory %>
  <%= f.text_field :inventory %>
</div>
<div class="form_field">
  <%= f.label :price %>
  <%= f.text_field :price %>
</div>
<div class="form_action">
  <%= f.submit %>
<% end %>
</div>
<%= link_to "Delete!", @product, method: :delete, class: "delete" %>
</div>

app/views/products/index.html.erb
<link rel='stylesheet' type='text/css' href='/assets/stylesheets/application.css'>
<h2><%= link_to @company.name, company_path(@company)%></h2>
<div class="logo" ><%= image_tag @company.logo_url, class:"company-logo"%>
</div>

<h3>Products</h3>
  <div class="product_table">
    <%= table_for @products , :html => {
  :class => "table table-hover"} do -%>
  <% columns :name, :description, :inventory, :vendor, :price  %>
<% end %>
</div>
<%= link_to "add products", new_company_product_path %>
<%= link_to "delete products", @company_product_path, method: :destroy %>

app/views/products/new.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        Companies
      </a>
    </div>
  </div>
</nav>

<h2>New Product for <%= @company.name %></h2>

<div class="container">
  <%= form_for [@company, @product] do |f| %>

  <div class="form_field">
    <%= f.label :vendor_name %>
    <%= f.text_field :vendor %>
  </div>
  <div class="form_field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form_field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="form_field">
    <%= f.label :inventory %>
    <%= f.text_field :inventory %>
  </div>
  <div class="form_field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="form_action">
    <%= f.submit %>
    <% end %>
  </div>

</div>

app/views/products/show.html.erb
<h2><%= @product.name %> <%= link_to("edit", edit_product_path(@product)) %></h2>

<h3><%= link_to @product.company.name, @product.company %></h3>